-- Aggiornamento DB per Funzionalità Memora v2
-- Esegui in Supabase > SQL Editor

-- 1. Aggiornamento Tabella TASKS (se non esiste la crea, se esiste aggiunge colonne)
create table if not exists tasks (
  id bigint generated by default as identity primary key,
  user_id text not null,
  text text not null,
  time text,
  completed boolean default false,
  category text default 'generic', -- farmaci, pasto, riposo, passeggiata, appuntamento
  recurrence text default 'none', -- daily, weekly, none
  created_at timestamptz default now()
);

-- Policy RLS per Tasks
alter table tasks enable row level security;
drop policy if exists "Allow all access to tasks" on tasks;
create policy "Allow all access to tasks" on tasks for all using (true);

-- 2. Tabella AI_CHAT_HISTORY (per persistenza conversazioni AI)
create table if not exists ai_chat_history (
  id bigint generated by default as identity primary key,
  user_id text not null,
  role text not null, -- user, assistant
  content text not null,
  created_at timestamptz default now()
);

-- Policy RLS per AI Chat
alter table ai_chat_history enable row level security;
drop policy if exists "Allow all access to ai_chat_history" on ai_chat_history;
create policy "Allow all access to ai_chat_history" on ai_chat_history for all using (true);

-- 3. Tabella MOOD_HISTORY (se non esisteva già in altri script, la definiamo qui)
create table if not exists mood_history (
  id bigint generated by default as identity primary key,
  user_id text not null,
  mood text not null, -- happy, neutral, sad
  created_at timestamptz default now()
);

-- Policy RLS per Mood History
alter table mood_history enable row level security;
drop policy if exists "Allow all access to mood_history" on mood_history;
create policy "Allow all access to mood_history" on mood_history for all using (true);

-- 4. Aggiunta colonna bio e privacy a PROFILES (se mancano)
alter table profiles add column if not exists bio text;
alter table profiles add column if not exists privacy_settings jsonb default '{"hide_location": false, "hide_email": false}';
